### PR TITLE
Fix raw_query for mock

### PR DESCRIPTION
**Pull request by Buckram123**
This PR aims at fixing raw_query method for mock env

### CODE REVIEW

**Comment by Kayanski** [comment]
> This PR aims at fixing raw_query method for mock env

Could you elaborate what this is for ?

**Comment by Buckram123** [comment]
> > This PR aims at fixing raw_query method for mock env
> 
> Could you elaborate what this is for ?

Wanted to cw2 raw query in mock env, to see what contract is that addr, got error instead: `Error: Error parsing into type alloc::vec::Vec<u8>: Invalid type`.

**Comment by Kayanski** [comment]
> > > This PR aims at fixing raw_query method for mock env
> > 
> > 
> > Could you elaborate what this is for ?
> 
> Just a bugfix. Wanted to cw2 raw query in mock env, to see what contract is that addr, got error instead: `Error: Error parsing into type alloc::vec::Vec<u8>: Invalid type`.

Oh, so the to_json_binary function was not working properly ?

**Comment by Buckram123** [comment]
> > > > This PR aims at fixing raw_query method for mock env
> > > 
> > > 
> > > Could you elaborate what this is for ?
> > 
> > 
> > Just a bugfix. Wanted to cw2 raw query in mock env, to see what contract is that addr, got error instead: `Error: Error parsing into type alloc::vec::Vec<u8>: Invalid type`.
> 
> Oh, so the to_json_binary function was not working properly ?

No, it was trying to deserialize raw query response into `Vec<u8>`, but it can succeed only if response was `b"[1, 2, 3]"`, not if it's `b"{"foo": "bar"}`

**Review by Kayanski — APPROVED** [review]

**Pull request merged**
