### PR TITLE
Rollkit

### PR DESCRIPTION
**Pull request by Kayanski**
This PR aims at integrating rollkit inside cw-orch.

For this integration, I used : 
- https://rollkit.dev/tutorials/cosmwasm
- celestia/v0.15.0.beta.1 for the Mocha testnet node
- wasmd/v0.50.0 for the node (which opens up port 9290 locally)

I modified : 
- In `init.sh` script, I replaced all occurences of `stake` by `uwasm` to be able to pay for gas with the created mnemonic/address
- I used the generated genesis mnemonic of wasmd as `LOCAL_MNEMONIC`

### CODE REVIEW

**Comment by CyberHoward** [comment]
> I modified :
> 
> * In `init.sh` script, I replaced all occurences of `stake` by `uwasm` to be able to pay for gas with the created mnemonic/address
> * I used the generated genesis mnemonic of wasmd as `LOCAL_MNEMONIC`
Were these modifications upstreamed?

**Comment by Kayanski** [comment]
> > I modified :
> > 
> > * In `init.sh` script, I replaced all occurences of `stake` by `uwasm` to be able to pay for gas with the created mnemonic/address
> > * I used the generated genesis mnemonic of wasmd as `LOCAL_MNEMONIC`
> >   Were these modifications upstreamed?

Not sure what you're saying here. The init.sh oart yes, the local mnemonic part is something the user should do

**Comment by CyberHoward** [comment]
Then that should prefably be documented as well in the doc that you added (how to get the local mnemonic if following the tutorial)

**Comment by adairrr** [comment]
Is `ROLLKIT_1` going to be the best name for this network configuration given that it's always run locally?

Should we include details on connecting to a hosted rollup?

**Comment by CyberHoward** [comment]
> Is `ROLLKIT_1` going to be the best name for this network configuration given that it's always run locally?
> 
> Should we include details on connecting to a hosted rollup?

Our documentation should follow their documentation imo. Otherwise we need to document too much overlapping stuff and if they are not following the rollkit docs then they probably know what they are doing and they can figure out stuff themselves, like a hosted rollup.

**Review by CyberHoward — APPROVED** [review]

**Pull request merged**
